### ISSUE TITLE
col-lg-10 only 83.333 even if there is no block on the right side

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#13]
Hi Gareth,

I installed Shoehorn version 3.0.0.2 in Moodle 3.0 (Build: 20151116).
The width of col-lg-10 in topic 1 > Assignment > Grading is 83.3333% although there is no block on the right side and two blocks are docked.
How can col-lg-10 be changed to 100% if there are no blocks on the right side? I would like to use the red polygon (see screenshot)
![col-lg-10 only 83 3333 how to make it 100](https://cloud.githubusercontent.com/assets/8261898/11888870/4f25f804-a58e-11e5-8c1f-fbb9b2290e23.jpg)

With kind regards,
Hartmut

**Comment by hartmut1s** [comment]
Hi Gareth,

In Quiz > Edit quiz I can see the marks.
![marks of a question](https://cloud.githubusercontent.com/assets/8261898/11889875/ae1843e8-a599-11e5-8ab9-a4d7bfe5a6d5.jpg)

This is not possible after selecting the edit icon, but it's possible in the Clean theme.
![editing marks](https://cloud.githubusercontent.com/assets/8261898/11889893/e62db7c2-a599-11e5-9e1a-614e8379bb64.jpg)

I was unable to figure out the CSS to make the mark of a question readable while editing.
With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Thank you for reporting the issues, I'll look into them.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Fixed Quiz bit in: https://github.com/gjb2048/moodle-theme_shoehorn/commit/ecff65157bdbf8c48b3b5a59c812ea6c1fbedc28

**Comment by gjb2048** [comment]
Fixed blocks and stuff: https://github.com/gjb2048/moodle-theme_shoehorn/commit/2e04a17f3e7ad020b539c484a1c27e58f0932f6e
