### ISSUE TITLE
Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#15]
Hi Gareth,

Today we upgraded our DE site to Moodle 3.0.1. I can access the site and everything thing seems to be normal except for cron which doesn't complete. When debug is on, the last line of the error message is:
Fatal error: Can't use function return value in write context in /home/pibceduc/public_html/theme/shoehorn/classes/toolbox.php on line 127

I posted the complete debug message in https://moodle.org/mod/forum/discuss.php?d=325152#p1306426

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

I have been progressively fixing things after adding TravisCI support: https://travis-ci.org/gjb2048/moodle-theme_shoehorn - which mentioned that sort of error.  I fixed it late last night, please upgrade.

Are you using the theme on a production site?  The stability is beta at the moment and I do not recommend that it is production ready.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Hi Hartmut,

The lowest version I'm testing Shoehorn on for M3.0 is PHP 5.4: https://travis-ci.org/gjb2048/moodle-theme_shoehorn.

Cheers,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

I installed the latest version of your theme Shoehorn. Now cron is executed completely. I am very glad that you were able to update the theme and that the error is solved. This is a timely and very nice gift. 

With kind regards,
Hartmut
