### ISSUE TITLE
TOC in book module on the right side

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#16]
Hi Gareth,

Yesterday I saw that the table of content in the book module is on the right side. When I added
.path-mod-book .col-lg-10 {
    float: right;
}
the table of content moved to the left. There may be a more elegant way to solve this, but the CSS does what I want. 

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

The Book TOC is a fake block.  So gets put in the default (I believe) block region.  Thus its a matter of altering the 'incourse' layout file to have blocks on the left / adapting that layout to change for that module = not simple but do-able.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Hi Hartmut,

Is this still an issue please?

Kind regards,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

Yes, it is still an issue but it doesn't bother me as the custom CSS does the job (see my initial post). Therefore, I can live with this and the issue can be closed.

With kind regards,
Hartmut
