### ISSUE TITLE
Group members displayed below groups instead of right side of groups

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#17]
Hi Gareth,

In Shoehorn 3.0.0.4 the 2 boxes, one for the groups and the other one for the group members are displayed vertically (/group/index.php).
![wrong display](https://cloud.githubusercontent.com/assets/8261898/12077291/d59e8968-b228-11e5-989d-637a04f7cfa2.jpg)
Both boxes should be next to each other, which happens when I select "Add/remove users" at the bottom of that page. I hope it's not too difficult to fix.
With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Fixed in https://github.com/gjb2048/moodle-theme_shoehorn/commit/828ffd45a84b1963601945d9868f6d75698d1ffc - also done lots of other changes and added the 'layout' setting (Look and feel settings) so you can have side-pre on the left.

Cheers,

Gareth

**Comment by gjb2048** [comment]
On your test server, just use the code from 'master'.

**Comment by hartmut1s** [comment]
Hi Gareth,

I tried to install the latest Shoehorn version on my test server and got an error message:
Fatal error: Call to undefined method theme_shoehorn\output\core_renderer_maintenance::get_setting() in C:\M3.0\apps\moodle\htdocs\theme\shoehorn\classes\toolbox.php on line 78

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Thanks for letting me know Hartmut, please update and it should be fixed.  Kind regards, Gareth.

**Comment by hartmut1s** [comment]
Hi Gareth,

Thanks a lot for your fast response. I was able to install the updated version of Shoehorn on my test server. It looks good.

With kind regards,
Hartmut
