### ISSUE TITLE
Admin can no longer "login as"

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#18]
Hi Gareth,

Sorry to bother you again. I am using the latest version of Shoehorn from Github. Another admin at our DE site could log in but he saw only the header with the navigation menu. The body of the page was completely missing. When he switched to Clean, he saw the complete page.

Using Mozilla Firefox, I logged in as admin and wanted to use the feature "login as" to see it from a student's perspective. The URL is: http://pibc-edu.com/course/loginas.php?id=1&user=228&sesskey=5sO1mZztHV#cm_submenu_18

Here is a screenshot.
![admin can no longer login as](https://cloud.githubusercontent.com/assets/8261898/12085469/3af702ac-b30c-11e5-92c6-8fdcf24095e6.jpg)

Here is the complete error message.
[error message - login as.pdf](https://github.com/gjb2048/moodle-theme_shoehorn/files/76944/error.message.-.login.as.pdf)

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Sorry, but I cannot replicate.  By going to a course and looking at the enrolled users, picking a user, then under 'Administration', picking 'Log in as'.  It works and displays the screen.  This is in Chrome so will try in FireFox later.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Cannot replicate in FireFox.

**Comment by hartmut1s** [comment]
Hi Gareth,

Thank you for looking into this issue. The issue doesn't occur all the time. So I am not surprised that you couldn't replicate it.
As an admin I did further testing today. Out of 12 students, 10 students passed the test, i.e., I could log in as. With two students, I got only the navigation bar without the login/logout. When I click on "Dashboard," only the navigation bar is visible. In a new tab I switched to Clean and the complete page showed up.

I purged the site several times, switched between Shoehorn and Clean and finally I could login as one of the two students, but I was unable to do this for the other student and the other admin (that I mentioned in a previous post).

What I suspect is that the Moodle DB somehow stored an incorrect sesskey. Purging the site doesn't help. Is there any other way to clean up or "reset" the sesskey for particular users? 

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Please could you risk developer level debugging and that should give a stack trace to look at when the problem happens.

I think the sesskey relates to the current user.

Cheers,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

Here is the debug message:
Fatal error: Class 'theme_shoehorn\output\core_text' not found in /home/pibceduc/public_html/theme/shoehorn/classes/output/core_renderer.php on line 839

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Thanks.  Please put a back slash in front of 'core_text' here: https://github.com/gjb2048/moodle-theme_shoehorn/blob/master/classes/output/core_renderer.php#L839-L840 - purge all caches and that should solve the problem.  I'll fix tomorrow.

Cheers,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

Thanks for the temporary fix. It worked for the other student. Regarding the other admin I am waiting for his feedback, but I expect that this problem is now solved. Thanks for the prompt response.

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Is this still an issue please?

Kind regards,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

This is no longer an issue and can be closed.

With kind regards,
Hartmut
