### ISSUE TITLE
Invalid get_string() identifier

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#20]
Hi Gareth,

When I installed Shoehorn version 3.0.1.1 (2015112408), I got the following debug message:

Invalid get_string() identifier: 'findcoursecontent' or component 'theme_essential'. Perhaps you are missing $string['findcoursecontent'] = ''; in /lang/en/theme_essential.php?
line 349 of \lib\classes\string_manager_standard.php: call to debugging()
line 6675 of \lib\moodlelib.php: call to core_string_manager_standard->get_string()
line 76 of \theme\shoehorn\layout\default.php: call to get_string()
line 1016 of \lib\outputrenderers.php: call to include()
line 946 of \lib\outputrenderers.php: call to core_renderer->render_page_layout()
line 164 of \my\index.php: call to core_renderer->header()

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Ops!

**Comment by gjb2048** [comment]
Thanks for reporting Hartmut.  Patch soon.  If you want to change yours locally, change to 'theme_shoehorn' on line 76 of default.php then 'Purge all caches'.  String is in the language file.

**Comment by gjb2048** [comment]
Updated in: https://moodle.org/plugins/pluginversion.php?id=10857

Fixed in: https://github.com/gjb2048/moodle-theme_shoehorn/commit/ad26c994484430f541f8b7e7b4c0b8de0bf1234a
