### ISSUE TITLE
Trouble with unordered lists in section headings

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#21]
Hi Gareth,

We have Moodle 3.0.1 (Build: 20151221) installed and use the theme Shoehorn version 3.0.1.1.1 (2015112409) . Two of our instructors like to use unordered lists in section headings. Before they save the section heading it looks like this (looks okay):

![unordered list before saving](https://cloud.githubusercontent.com/assets/8261898/15002620/57316a3c-11e6-11e6-926c-2e0ede9b69ed.jpg)

And this is what the instructors get after saving the section heading:

![unordered list after saving](https://cloud.githubusercontent.com/assets/8261898/15002624/682fbd34-11e6-11e6-9a0f-28348d8b50ff.jpg)

How can I get rid of the circles or the square? It looks as if two lists are implemented, not one. I switched to Clean which looked okay both times. 

With kind regards,

Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

I'll have a look when I can.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Hartmut,

What editor are you using please?

I can't quite replicate it, but something odd is going on.  Do you have any custom CSS?  Is there a page (say using site page feature) whereby I could see on your site the problem (no need to edit)?

Kind regards,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,
Thank you for your reply. I am using Google Chrome, but this behavior also occurs in Mozilla Firefox. Yesterday I saw a Moodle tracker that was resolved about 9 months ago, which changed the base theme and the bootstrapbase theme. I couldn't find the tracker # today.

Here is a link to the Custom CSS that I use in Shoehorn:
https://www.dropbox.com/s/pd27pyu01eu8r4l/Shoehorn%20-%20Custom%20CSS.txt?dl=0

I sent you the login details in a message.

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

The circle and square I need to address, however, the right filled chevron is from custom FontAwesome CSS:

![2016-05-05 18_00_21-course_ scie 101 general science su 16](https://cloud.githubusercontent.com/assets/1058419/15050475/ef87a110-12eb-11e6-9185-1b233cdb4031.png)

Thus is an issue locally.  The theme issue is that there is not a match between the list style type in the editor and on the page.  If you wanted to keep the FontAwesome ones but scrap the list ones on the course, then use 'list-style-type: none' (I think) on the fix I'll do for this.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Looks like Shoehorn is missing the Moodle LESS with the selectors:

.course-content li.section li.activity ul

etc.  This is also true of the Bootstrap theme.

**Comment by gjb2048** [comment]
Hi Hartmut,

This: https://github.com/gjb2048/moodle-theme_shoehorn/commit/b7a3542904339c5155a6a4621572974f24706936 - should fix the issue with the wrong symbol being used in the course.  Not sure about the FontAwesome bit until you tell me.

Kind regards,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,
Thank you for the fix regarding the wrong symbol in the course heading section. The symbols changed.

Actually, I want to see only one symbol, not two. In my initial post, the first screenshot was from the editor and showed one list style.
After saving, another list style is added in the section heading of a topic. So for each line, there are actually two list styles applied where there should be only one list style. Below is what it looks like now:
![2 list styles applied in section heading](https://cloud.githubusercontent.com/assets/8261898/15061037/03958b3a-1374-11e6-94b6-0439a3760ba7.jpg)

How is it possible to get rid off the icons in the five red circles?

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

I tried the test username and password you gave me and its not working any more so cannot double check where that CSS is coming from.  I looked in the custom CSS you sent me and its not there.  As previously posted, there is some custom CSS (in another plugin perhaps): https://cloud.githubusercontent.com/assets/1058419/15050475/ef87a110-12eb-11e6-9185-1b233cdb4031.png that is causing this issue.  That CSS is not coming from the distributed theme as far as I can tell.

Kind regards,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

Sorry Gareth. I deleted the user account too soon. Now I restored it again. It should work with the same credentials. 
I will also try to figure out where the CSS is coming from. 

Thank you for your effort to solve the issue.

With kind regards,
Hartmut

**Comment by hartmut1s** [comment]
H Gareth,

Here is a screenshot from the same online class and no changes regarding plugins or filters.
![clean theme - section heading with ul](https://cloud.githubusercontent.com/assets/8261898/15088507/7531ef26-1438-11e6-8d50-f99b475cb8be.jpg)
Only one list style is applied.
With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

I've just tried again with the same credentials and they did not work.

Kind regards,

Gareth

**Comment by hartmut1s** [comment]
Thank you, Gareth. Your latest fix solved the issue and I am glad that the theme Shoehorn looks nice.

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
No worries Hartmut :)
