### ISSUE TITLE
Block visibility issue with block, content, block layout.

### ISSUE THREAD

**Issue by sestrauss** [gjb2048/moodle-theme_shoehorn#23]
Using your fantastic theme, I get a dead zone for certain FF Window sizes. I have seen this on several Macs using various FF versions. However, I definitely see it using my Mac OS 10.9.5 system with FF 47.0.

I have attached a screen cast showing the issue with the Shoehorn theme, and the lack of such issue with the Clean theme.

Safari and Chrome do not have this problem.

[window resize issue.mp4.zip](https://github.com/gjb2048/moodle-theme_shoehorn/files/364096/window.resize.issue.mp4.zip)

**Comment by gjb2048** [comment]
FF = Firefox?

What version of Moodle and Shoehorn please?

I don't own a Mac so cannot replicate exactly, but will try on a PC.

**Comment by sestrauss** [comment]
Wow--that was quick. I was just looking that up to add it while you were responding. 

Moodle 3.0.4+ (Builde 20160520)
Shoehorn 3.0.1.2 (2015112410)

**Comment by gjb2048** [comment]
Ok, I can sort of replicate.  When it's blank, is this actually space and the content is much further down the page?

**Comment by sestrauss** [comment]
As a matter of fact, yes. I just found the content when I scrolled down. So then, I'm not sure if this is really a bug. However, I have had a couple of people who were very confused by the blank screen. Scrolling down is not at all obvious.

Also, I have been working in other browsers, and I may have seen the issue in Safari too since posting. However, it seems to happen much less often (if at all) in the other browsers.

**Comment by gjb2048** [comment]
I can replicate in Chrome and FF on Windows when no accordion blocks and 'block, content, block' layout.

**Comment by sestrauss** [comment]
So, if I change me block layout, will that fix this?

On Thu, Jul 14, 2016 at 12:37 PM, Gareth J Barnard <notifications@github.com
> wrote:

> I can replicate in Chrome and FF on Windows when no accordion blocks and
> 'block, content, block' layout.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gjb2048/moodle-theme_shoehorn/issues/23#issuecomment-232720406>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFQ-il-lgCGq9Lmx3KuhYwplCheCdSIsks5qVmWzgaJpZM4JMivl>
> .
>



-- 
Sharon Strauss
Instructional Technology Services
IITS
Haverford College <http://iits.haverford.edu>
sstrauss@haverford.edu
610-896-4916

IITS staff will never ask for your password.
The privacy of your password enhances the privacy of our entire community
and the integrity of our technology environment.
Check us out on the web - http://www.haverford.edu/iits
Read our blog -  http://iits.haverford.edu/instructionaltechnology/

**Comment by gjb2048** [comment]
Yes.  But there is a bug to fix.

**Comment by gjb2048** [comment]
NTS: M3.0 and M2.9 fix todo.

**Comment by gjb2048** [comment]
Fixed in M2.9 and M3.0 versions.

**Comment by sestrauss** [comment]
Thanks!

**Comment by asavoth** [comment]
We still seem to be encountering similar dead zones. Here are two screen shots to illustrate what happens during resizing in Chrome on both PC and Mac. In one case, the blocks disappear all together and aren't relocated to the bottom of the scroll. 
<img width="973" alt="screen shot 2016-08-17 at 3 56 17 pm" src="https://cloud.githubusercontent.com/assets/21089187/17751982/bae2e124-6497-11e6-9808-559a723c8f03.png">
<img width="719" alt="screen shot 2016-08-17 at 3 56 36 pm" src="https://cloud.githubusercontent.com/assets/21089187/17751981/badffedc-6497-11e6-903d-7f05e63e1f0c.png">
