### ISSUE TITLE
Assignment grade view - header collapsed

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#24]
Hi Gareth,

I appreciate that you work on Shoehorn 3.1 and I hope you will be able to solve a problem that you already solved in Essential (see forum post on July 29 - https://moodle.org/mod/forum/discuss.php?d=334985#p1356021). I just downloaded the Shoehorn 3.1 beta version and installed it at a test site. When I go to an assignment > Grades (http://127.0.0.1/moodle/mod/assign/view.php?id=1155&action=grader), I cannot see the details of the header when the zoom is 100%. When the zoom is 300%, the header is readable. Below are two screenshots, the first with Shoehorn, the second with Clean.

![assignment - grade view shoehorn 3 1 beta](https://cloud.githubusercontent.com/assets/8261898/17353986/c8f3abec-5987-11e6-93e1-8dc94a46d2d4.jpg)

![assignment - grade view clean theme](https://cloud.githubusercontent.com/assets/8261898/17353990/cf99e16e-5987-11e6-8e4b-5d6e0abc547c.jpg)

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Thanks, investigating....

Gareth

**Comment by gjb2048** [comment]
Odd, as applied https://github.com/bmbrands/theme_bootstrap/commit/c1159b6d19232802f6ee9462c8089e1e85c57a05

**Comment by gjb2048** [comment]
https://github.com/gjb2048/moodle-theme_essential/commit/e39f92fdcb08159d051c8cb932a6b9a6bb569672 pertains to Essential's removal of mod assign styles, this does not happen in Shoehorn.

**Comment by hartmut1s** [comment]
Thanks for working on the assignment grader issue in Shoehorn. If I reduce the screen size significantly, I can see the complete header. If I increase the screen size, the header will be collapsed again.

**Comment by gjb2048** [comment]
Thanks Harmut, useful information.

**Comment by gjb2048** [comment]
Ok, this sort of helps, but means everything inline:

@media (max-width: 767px)
.path-mod-assign [data-region="grading-navigation-panel"], .path-mod-assign [data-region="review-panel"], .path-mod-assign [data-region="grade-panel"], .path-mod-assign [data-region="review-panel"].collapsed + [data-region="grade-panel"], .path-mod-assign [data-region="grade-actions-panel"] {
    position: inherit;
    width: 100%;
    top: 0;
    left: 0;
    right: auto;
    overflow: auto;
    height: auto;
    margin-bottom: 1em;
}

**Comment by hartmut1s** [comment]
Thanks for the suggestion. I added your CSS in Custom CSS without any other code, purged cache and still saw the collapsed header in assignment grader. When I inspected the div's, position switches from inherit to absolute. This also happens when I used
position: inherit !important;
It is later overridden.

Then I left out the media and tried

.path-mod-assign [data-region="grading-navigation-panel"], .path-mod-assign [data-region="review-panel"], .path-mod-assign [data-region="grade-panel"], .path-mod-assign [data-region="review-panel"].collapsed + [data-region="grade-panel"], .path-mod-assign [data-region="grade-actions-panel"] {
position: relative;
width: 100%;
top: 0;
left: 0;
right: auto;
overflow: auto;
height: auto;
margin-bottom: 1em;
}

![assignment grader view with position relative](https://cloud.githubusercontent.com/assets/8261898/17420412/d1c23d74-5ae5-11e6-9cf3-112dda6a6fe0.jpg)

Now I can see the complete header but I lost the scrollbar and the text box for the grade moved too much to the right (see screenshot)

**Comment by gjb2048** [comment]
Hi Hartmut,

Oh, that was not a suggested fix, just me making notes about the problem.

G

**Comment by gjb2048** [comment]
Ouch, the core code is HORRIBLE.

**Comment by gjb2048** [comment]
Hi Hartmut,

I think I've fixed (as well as can be) in https://github.com/gjb2048/moodle-theme_shoehorn/commit/e0e3e9d16ddf98207347c6f7298a497fdef03526.

G

**Comment by hartmut1s** [comment]
Hi Gareth,

You fixed this bug. Thanks a lot for it. I am glad that the grader view of assignments is now correct in Shoehorn. Just in time as we plan to upgrade to Moodle 3.1 in a week. Yes, I know Shoehorn is still in beta but it looks good and I prefer to offer the same feel and look to staff & faculty with Moodle 3.1.

Thanks again for maintaining the theme Shoehorn.
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

Now official 'release candidate' version: https://moodle.org/mod/forum/discuss.php?d=337719

Cheers,

Gareth
