### ISSUE TITLE
Ordered/Unordered list not showing

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#25]
Hi Gareth,

Using Atto, I can't see the numbers of an ordered list or the bullet points with Shoehorn 3.1.0.1 (2016072100) in Moodle 3.1.1 (Build: 20160811). The first screenshot is taken from Shoehorn, the second from Clean.
![number missing in ordered list - shoehorn](https://cloud.githubusercontent.com/assets/8261898/17890992/a762d5ca-697c-11e6-9870-e8186b0042c0.jpg)
![number showing in ordered list - clean theme](https://cloud.githubusercontent.com/assets/8261898/17890995/a9ce6a68-697c-11e6-92c1-dd532fa00e38.jpg)

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Appears to be missing margin CSS for some reason.

**Comment by gjb2048** [comment]
BS3 seems to have lost side margin values: https://github.com/twbs/bootstrap/blob/v3.3.7/less/type.less#L157-L166 -> https://github.com/twbs/bootstrap/blob/v2.3.2/less/type.less#L105-L108

**Comment by gjb2048** [comment]
Hi Hartmut,

Fixed in https://github.com/gjb2048/moodle-theme_shoehorn/commit/3f176b6ff26bb474e5f99e416da9f16c0fb83a37 and will be in the next release.

G

**Comment by hartmut1s** [comment]
Hi Gareth,

Thank you for the fix. You are very fast. It's just amazing and very
encouraging to see how you maintain the theme.

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
No worries Hartmut.
