### ISSUE TITLE
Display of true/false question in Lesson module

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#26]
Hi Gareth,

Both answers of the true/false question in the Lesson module are displayed in one line in Shoehorn.
![lesson - true false shoehorn](https://cloud.githubusercontent.com/assets/8261898/17969605/3e594b0e-6b16-11e6-8e8b-ef22c2ee60b6.jpg)

In Clean it looks like this:
![lesson - true false clean](https://cloud.githubusercontent.com/assets/8261898/17969615/4db675d6-6b16-11e6-8c76-5ac4453640cb.jpg)

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Hi Hartmut,

On a pragmatic level is Shoehorn actually better as there is less space wastage and less scroll of death?

G

**Comment by hartmut1s** [comment]
Hi Gareth,

Thank you for your reply. I would not mind having true/false in one line. Unfortunately, it's not consistent across browsers. Here is true/false with Shoehorn in Google Chrome
![lesson - true false shoehorn](https://cloud.githubusercontent.com/assets/8261898/17988019/c8d9db9a-6b66-11e6-9f40-6fbbd79f7d05.jpg)

This is the display of the same page in Mozilla Firefox
![lesson - true false shoehorn in ff](https://cloud.githubusercontent.com/assets/8261898/17988037/e7a50fe0-6b66-11e6-9947-37e30563a927.jpg)

In FF the radio buttons of the true/false question in the Lesson module are not displayed properly. I do not mind if they are displayed in one line but how can this be accomplished in FF?

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
Ok Hartmut,

I'll look into it.

G

**Comment by gjb2048** [comment]
Missing in forms.less:

````
.mform .fcheckbox > span,
.mform .fradio > span,
.mform .fgroup > span {
    display: inline-block;
    margin-top: 5px;
}
````
