### ISSUE TITLE
Unordered list not showing in Dataform activity description

### ISSUE THREAD

**Issue by hartmut1s** [gjb2048/moodle-theme_shoehorn#27]
Hi Gareth,

We use the Moodle plugin Dataform. In a Dataform activity, an unordered list is not displayed with Shoehorn, but I can see it in Clean.

With kind regards,
Hartmut

**Comment by hartmut1s** [comment]
It's a problem with margins again. It's barely visible in the screenshot below.
![ul in dataform](https://cloud.githubusercontent.com/assets/8261898/18032162/d342c922-6d3f-11e6-8d31-94e2a167b82e.jpg)

**Comment by gjb2048** [comment]
Hi Hartmut,

Ok, initially, no M3.1 version: https://moodle.org/plugins/pluginversions.php?plugin=mod_dataform.

G

**Comment by gjb2048** [comment]
Hi Hartmut,

Installed the module but have no idea how to replicate the issue.  Please provide instructions / test course.

Thanks,

Gareth

**Comment by hartmut1s** [comment]
Hi Gareth,

After I reported the missing ol/ul in Dataform, I saw that ol/ul is also missing in the assignment activity. My best guess is that the code gets overridden, because when I added 
ul, ol {
    margin-left: 25px;
}
in custom CSS, the display is correct. 

If you still need or want to replicate the issue in Dataform, start a new Dataform activity, save it without changing anything and select preset. I uploaded a preset at
https://www.dropbox.com/s/x9g9zdi94tabbu4/Journal_%28For_at_least_10_days%29-dataform-preset-20160828_2131-without-user-data.mbz?dl=0
If you load it into the Dataform activity and apply the preset, you should see a description in the Overview view without ol/ul.

With kind regards,
Hartmut

**Comment by gjb2048** [comment]
So the assignment issue is a separate one?

**Comment by gjb2048** [comment]
Hi Hartmut,

I'm sorry, but I'm still lost!  Please could you provide step by step instructions on how to replicate.  This is what I have in the Clean theme with the view of the preset (so that I'd see the list and know its there):

![2016-08-29 20_50_49-start](https://cloud.githubusercontent.com/assets/1058419/18065170/9df58cc8-6e2a-11e6-8d44-e9dfc00c637b.png)

G

**Comment by gjb2048** [comment]
Also please provide a screenshot and instructions for the assignment issue in a new issue, I'm lost as cannot see a list there either.

**Comment by hartmut1s** [comment]
Not a bug as I found out when I tested the activity at my test site. Probably I didn't install the latest version of Shoehorn correctly. I will do this again. Sorry for the confusion.
