### ISSUE TITLE
Strict standards issue with user menu

### ISSUE THREAD

**Issue by mike-grant** [gjb2048/moodle-theme_shoehorn#9]
I've just downloaded the latest version for Moodle 2.7 (2.7.1.1) from Moodle.org and installed it for the first time.

Throws a strict standards error with the user menu,

Strict Standards: Declaration of theme_shoehorn_core_renderer::user_menu() should be compatible with theme_bootstrap_core_renderer::user_menu($user = NULL, $withlinks = NULL) in C:\xampp\htdocs\moodle\theme\shoehorn\renderers\core_renderer.php on line 1034

**Comment by gjb2048** [comment]
You have installed the M2.8 version of Bootstrap, please install the M2.7 version.  I believe I state on the plugins page.  Maybe the Readme is out of date.

**Comment by mike-grant** [comment]
I've double checked the Readme and Moodle.org

Moodle.org is stating that the latest version for 2.7 is 2.7.1.1 and the latest for 2.8 is 2.8.0.1

Thanks

**Comment by gjb2048** [comment]
Sorry, I mean the parent Bootstrap theme.

**Comment by gjb2048** [comment]
Readme states the version of Bootstrap you need: https://github.com/gjb2048/moodle-theme_shoehorn/tree/MOODLE_27#required-version-of-bootstrap-3

**Comment by gjb2048** [comment]
Note to self: Needs to be clearer and M2.8 version needs updating in this respect.

**Comment by gjb2048** [comment]
Ok, https://moodle.org/plugins/download.php/6987/theme_bootstrap_moodle27_2014100300.zip is unavailable.  Humm.

**Comment by mike-grant** [comment]
I guess this can be closed as an issue really, the issue with the strict standards is caused by me not using the correct versions, so hardly a fault with the theme.

**Comment by gjb2048** [comment]
Oh no, it's a version control issue as parent theme is not matching on version and M2.7 version seems to have gone!  So, please use the 'Download ZIP' on: https://github.com/gjb2048/theme_bootstrap/tree/master_M27 to get a version that should not have the error.

**Comment by gjb2048** [comment]
Fixed in V2.7.1.3, just about to be released.
